### ISSUE TITLE
Zathura doesn't diplay differently sized pages correctly

### ISSUE THREAD

**Issue by jc-SpaceXp** [pwmt/zathura#695] opened 2024-06-13 06:55 UTC
See images below: 

## Expected (firefox pdf viewer)
![wider_page_zathura_expected](https://github.com/pwmt/zathura/assets/29800749/23da6a76-6989-4092-b8a3-36590ae87644)

## Actual
![wider_page_zathura_actual](https://github.com/pwmt/zathura/assets/29800749/2bd1ccb9-a585-4d44-9609-521efca248b2)

Appears that first image the page is A4 and the second is A3 and Zauthra is failing to scale the page correctly. Zathura just crops out an A4 section from the A3 page it seems. 

Link to pdf: https://www.st.com/resource/en/datasheet/stm32g431c6.pdf

Couldn't find any keyboard shortcut to resolve the issue either

**Comment by majutsushi** [comment] 2024-11-11 00:43
This seems to be a duplicate of #602

**Closed** 2024-12-08 17:51 UTC
